# Generated by Django 5.2.14 on 2026-05-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_familymember_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='birth_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
