# Generated by Django 5.2.14 on 2026-05-22 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_familymember_tree'),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='family.familytree'),
        ),
    ]
